### ISSUE TITLE
Keyerror

### ISSUE THREAD

**Issue by aiyeshi** [capellaspace/jupyter-notebooks#6]
Hi, when I run the jupyter, an error occurred: 
accesstoken = r.json()["accessToken"]

KeyError: 'accessToken'
I have an Capella account.
Could you tell me how to solve the problem?

**Comment by jason-brown904** [comment]
Hi Aiyeshi,

Can you provide more details? Such as which Jupyter Notebook you are running and which cell gives the error. Additionally, please ensure that you have a "credentials.json" file with your username and password in the same directory as the notebook.

Kind Regards,
Capella Space

**Comment by aiyeshi** [comment]
Hi，Jason-brown， I run the Capella-API-Rotterdam-search-order-download-example.ipynb. But I only copied the first few lines of code from the ipynb file and saved as a python file (test.py). Then I placed the credentials.json file in the same directory as the python file(test.py) and run the program test.py in the pycharm, such as : 

# test.py 

import requests
import json

# JSON utility function
def p(data):
    print(json.dumps(data, indent=2))

# Capella API endpoints
URL = 'https://api.capellaspace.com'
token = '/token'
collections = '/catalog/collections'
catsearch = '/catalog/search'
orders = '/orders/'

# Load my username and password
with open('credentials.json') as f:
    data = json.load(f)
    username = data['username']
    password = data['password']

# Get the token 
r = requests.post(URL + token, 
                  headers = {'Content-Type': 'application/x-www-form-urlencoded'}, auth=(username,password))

accesstoken = r.json()["accessToken"]

# Print the token
print("Access Token: " + accesstoken)
Duplicate of #

headers = {'Authorization':'Bearer ' + accesstoken}

# See what collections are available
r = requests.get(URL + collections, headers=headers)

# Print results
#p(r.json())

**Comment by jason-brown904** [comment]
Hi,

I went through the Notebook and it worked for me. It looks like you need to import urllib also. Please try that and if it doesn't work please send an email to support@capellaspace.com for further assistance.

Capella Space

**Comment by jason-brown904** [comment]
closed
